stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''
  GCP_IMAGE_REPO: $GCP_AR_URL/$GCP_PROJECT/docker/gitlab-mr-reviewer

build:
  image: docker:27.3.1-dind
  stage: build
  services:
    - docker:27.3.1-dind
  before_script:
    - until docker info; do sleep 1; done
  script:
    - GCP_IMAGE_TAG=`cat version.json | sed "s/[^0-9\.]//g"`
    - docker build -t $GCP_IMAGE_REPO:$GCP_IMAGE_TAG .
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  image: docker:27.3.1-dind
  stage: deploy
  services:
    - docker:27.3.1-dind
  before_script:
    - until docker info; do sleep 1; done
    - base64 -d $GKE_CICD_SA_KEY | docker login -u _json_key --password-stdin $GCP_AR_URL
  script:
    - GCP_IMAGE_TAG=`cat version.json | sed "s/[^0-9\.]//g"`
    - docker push $GCP_IMAGE_REPO:$GCP_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'