version: '3'

services:
  gitlab-mr-reviewer:
    build: .
    image: gitlab-mr-reviewer
    container_name: gitlab-mr-reviewer
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GITLAB_API_URL=${GITLAB_API_URL}
      - GITLAB_PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN}
      - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-opus-20240229}
      - PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - ./logs:/usr/src/app/logs